# Data Exploration

Rodrigo Hernandez Mota

In [1]:
% matplotlib inline

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from util.data_preparation import get_data, DataSets

## Get Data

In [2]:
data, submit = get_data()

In [4]:
print("\nData shape: {}".format(data.shape))

data.head()

Data shape: (595212, 58)

,target,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,ps_ind_09_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
7,0,2,2,5,1,0,0,1,0,0,...,9,1,5,8,0,1,1,0,0,1
9,0,1,1,7,0,0,0,0,1,0,...,3,1,1,9,0,1,1,0,1,0
13,0,5,4,9,1,0,0,0,1,0,...,4,2,7,7,0,1,1,0,1,0
16,0,0,1,2,0,0,1,0,0,0,...,2,2,4,9,0,0,0,0,0,0
17,0,0,2,0,1,0,1,0,0,0,...,3,1,1,3,0,0,0,1,1,0

In [5]:
data.describe()

,target,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,ps_ind_09_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
count,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,...,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000
mean,0.036448,1.900378,1.358943,4.423318,0.416794,0.405188,0.393742,0.257033,0.163921,0.185304,...,5.441382,1.441918,2.872288,7.539026,0.122427,0.627840,0.554182,0.287182,0.349024,0.153318
std,0.187401,1.983789,0.664594,2.699902,0.493311,1.350642,0.488579,0.436998,0.370205,0.388544,...,2.332871,1.202963,1.694887,2.746652,0.327779,0.483381,0.497056,0.452447,0.476662,0.360295
min,0.000000,0.000000,-1.000000,0.000000,-1.000000,-1.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,4.000000,1.000000,2.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,1.000000,1.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,5.000000,1.000000,3.000000,7.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000
75%,0.000000,3.000000,2.000000,6.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,...,7.000000,2.000000,4.000000,9.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000
max,1.000000,7.000000,4.000000,11.000000,1.000000,6.000000,1.000000,1.000000,1.000000,1.000000,...,19.000000,10.000000,13.000000,23.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [15]:
# columns

def print_col_info(df, col):
    def get_unique(values):
        desc = "Unique Values: "
        for val in np.unique(values):
            desc += "\n\t " + str(val)
        return desc
    def get_mean_std(values):
        return "\t Mean: " + str(np.mean(values)) +\
    "\n\t Std: " + str(np.std(values)) +\
    "\n\t Min val: " + str(np.min(values)) +\
    "\n\t Max val: " + str(np.max(values))
        
    info = """
    -----------------
    Column: {name}
    
    Data Type: {type}
    Desc:
    {desc}
    """
    values = df[col].values
    desc = get_unique(values) if isinstance(values[0], np.int64) else get_mean_std(values)
    print(info.format(
        name=col,
        type=type(values[0]),
        desc=desc
    ))
    

for col in data:
    print_col_info(data, col)

    -----------------
    Column: target

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 0
	 1


    -----------------
    Column: ps_ind_01

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 0
	 1
	 2
	 3
	 4
	 5
	 6
	 7


    -----------------
    Column: ps_ind_02_cat

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 -1
	 1
	 2
	 3
	 4


    -----------------
    Column: ps_ind_03

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 0
	 1
	 2
	 3
	 4
	 5
	 6
	 7
	 8
	 9
	 10
	 11


    -----------------
    Column: ps_ind_04_cat

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 -1
	 0
	 1


    -----------------
    Column: ps_ind_05_cat

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 -1
	 0
	 1
	 2
	 3
	 4
	 5
	 6


    -----------------
    Column: ps_ind_06_bin

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 0
	 1


    -----------------
    Column: ps_ind_07_bin

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 0
	 1


    -----------------
    Column: ps_ind_08_bin

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 0
	 1


    -----------------
    Column: ps_ind_09_bin

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 0
	 1


    -----------------
    Column: ps_ind_10_bin

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 0
	 1


    -----------------
    Column: ps_ind_11_bin

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 0
	 1


    -----------------
    Column: ps_ind_12_bin

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 0
	 1


    -----------------
    Column: ps_ind_13_bin

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 0
	 1


    -----------------
    Column: ps_ind_14

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 0
	 1
	 2
	 3
	 4


    -----------------
    Column: ps_ind_15

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 0
	 1
	 2
	 3
	 4
	 5
	 6
	 7
	 8
	 9
	 10
	 11
	 12
	 13


    -----------------
    Column: ps_ind_16_bin

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 0
	 1


    -----------------
    Column: ps_ind_17_bin

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 0
	 1


    -----------------
    Column: ps_ind_18_bin

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 0
	 1


    -----------------
    Column: ps_reg_01

    Data Type: <class 'numpy.float64'>
    Desc:
    	Mean: 0.610991377862
	 Std: 0.287642377526
	 Min val: 0.0
	 Max val: 0.9


    -----------------
    Column: ps_reg_02

    Data Type: <class 'numpy.float64'>
    Desc:
    	Mean: 0.439184357842
	 Std: 0.404263946148
	 Min val: 0.0
	 Max val: 1.8


    -----------------
    Column: ps_reg_03

    Data Type: <class 'numpy.float64'>
    Desc:
    	Mean: 0.551101841043
	 Std: 0.793505100745
	 Min val: -1.0
	 Max val: 4.0379450219


    -----------------
    Column: ps_car_01_cat

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 -1
	 0
	 1
	 2
	 3
	 4
	 5
	 6
	 7
	 8
	 9
	 10
	 11


    -----------------
    Column: ps_car_02_cat

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 -1
	 0
	 1


    -----------------
    Column: ps_car_03_cat

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 -1
	 0
	 1


    -----------------
    Column: ps_car_04_cat

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 0
	 1
	 2
	 3
	 4
	 5
	 6
	 7
	 8
	 9


    -----------------
    Column: ps_car_05_cat

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 -1
	 0
	 1


    -----------------
    Column: ps_car_06_cat

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 0
	 1
	 2
	 3
	 4
	 5
	 6
	 7
	 8
	 9
	 10
	 11
	 12
	 13
	 14
	 15
	 16
	 17


    -----------------
    Column: ps_car_07_cat

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 -1
	 0
	 1


    -----------------
    Column: ps_car_08_cat

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 0
	 1


    -----------------
    Column: ps_car_09_cat

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 -1
	 0
	 1
	 2
	 3
	 4


    -----------------
    Column: ps_car_10_cat

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 0
	 1
	 2


    -----------------
    Column: ps_car_11_cat

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 1
	 2
	 3
	 4
	 5
	 6
	 7
	 8
	 9
	 10
	 11
	 12
	 13
	 14
	 15
	 16
	 17
	 18
	 19
	 20
	 21
	 22
	 23
	 24
	 25
	 26
	 27
	 28
	 29
	 30
	 31
	 32
	 33
	 34
	 35
	 36
	 37
	 38
	 39
	 40
	 41
	 42
	 43
	 44
	 45
	 46
	 47
	 48
	 49
	 50
	 51
	 52
	 53
	 54
	 55
	 56
	 57
	 58
	 59
	 60
	 61
	 62
	 63
	 64
	 65
	 66
	 67
	 68
	 69
	 70
	 71
	 72
	 73
	 74
	 75
	 76
	 77
	 78
	 79
	 80
	 81
	 82
	 83
	 84
	 85
	 86
	 87
	 88
	 89
	 90
	 91
	 92
	 93
	 94
	 95
	 96
	 97
	 98
	 99
	 100
	 101
	 102
	 103
	 104


    -----------------
    Column: ps_car_11

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 -1
	 0
	 1
	 2
	 3


    -----------------
    Column: ps_car_12

    Data Type: <class 'numpy.float64'>
    Desc:
    	Mean: 0.379944815095
	 Std: 0.0583269063459
	 Min val: -1.0
	 Max val: 1.2649110641


    -----------------
    Column: ps_car_13

    Data Type: <class 'numpy.float64'>
    Desc:
    	Mean: 0.813264675636
	 Std: 0.224587907697
	 Min val: 0.2506190682
	 Max val: 3.7206260026


    -----------------
    Column: ps_car_14

    Data Type: <class 'numpy.float64'>
    Desc:
    	Mean: 0.276256274137
	 Std: 0.357153733267
	 Min val: -1.0
	 Max val: 0.6363961031


    -----------------
    Column: ps_car_15

    Data Type: <class 'numpy.float64'>
    Desc:
    	Mean: 3.06589944336
	 Std: 0.731365611482
	 Min val: 0.0
	 Max val: 3.7416573868


    -----------------
    Column: ps_calc_01

    Data Type: <class 'numpy.float64'>
    Desc:
    	Mean: 0.44975638932
	 Std: 0.287197845211
	 Min val: 0.0
	 Max val: 0.9


    -----------------
    Column: ps_calc_02

    Data Type: <class 'numpy.float64'>
    Desc:
    	Mean: 0.449589221991
	 Std: 0.28689324084
	 Min val: 0.0
	 Max val: 0.9


    -----------------
    Column: ps_calc_03

    Data Type: <class 'numpy.float64'>
    Desc:
    	Mean: 0.449848793371
	 Std: 0.287152744091
	 Min val: 0.0
	 Max val: 0.9


    -----------------
    Column: ps_calc_04

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 0
	 1
	 2
	 3
	 4
	 5


    -----------------
    Column: ps_calc_05

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 0
	 1
	 2
	 3
	 4
	 5
	 6


    -----------------
    Column: ps_calc_06

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 0
	 1
	 2
	 3
	 4
	 5
	 6
	 7
	 8
	 9
	 10


    -----------------
    Column: ps_calc_07

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 0
	 1
	 2
	 3
	 4
	 5
	 6
	 7
	 8
	 9


    -----------------
    Column: ps_calc_08

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 2
	 3
	 4
	 5
	 6
	 7
	 8
	 9
	 10
	 11
	 12


    -----------------
    Column: ps_calc_09

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 0
	 1
	 2
	 3
	 4
	 5
	 6
	 7


    -----------------
    Column: ps_calc_10

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 0
	 1
	 2
	 3
	 4
	 5
	 6
	 7
	 8
	 9
	 10
	 11
	 12
	 13
	 14
	 15
	 16
	 17
	 18
	 19
	 20
	 21
	 22
	 23
	 24
	 25


    -----------------
    Column: ps_calc_11

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 0
	 1
	 2
	 3
	 4
	 5
	 6
	 7
	 8
	 9
	 10
	 11
	 12
	 13
	 14
	 15
	 16
	 17
	 18
	 19


    -----------------
    Column: ps_calc_12

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 0
	 1
	 2
	 3
	 4
	 5
	 6
	 7
	 8
	 9
	 10


    -----------------
    Column: ps_calc_13

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 0
	 1
	 2
	 3
	 4
	 5
	 6
	 7
	 8
	 9
	 10
	 11
	 12
	 13


    -----------------
    Column: ps_calc_14

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 0
	 1
	 2
	 3
	 4
	 5
	 6
	 7
	 8
	 9
	 10
	 11
	 12
	 13
	 14
	 15
	 16
	 17
	 18
	 19
	 20
	 21
	 22
	 23


    -----------------
    Column: ps_calc_15_bin

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 0
	 1


    -----------------
    Column: ps_calc_16_bin

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 0
	 1


    -----------------
    Column: ps_calc_17_bin

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 0
	 1


    -----------------
    Column: ps_calc_18_bin

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 0
	 1


    -----------------
    Column: ps_calc_19_bin

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 0
	 1


    -----------------
    Column: ps_calc_20_bin

    Data Type: <class 'numpy.int64'>
    Desc:
    Unique Values:
	 0
	 1